import type { Activity } from './types';

/**
 * Minimal honest curated set, returned ONLY when no real source yields data.
 * Mirrors the client's curated dataset shape. `verifiedLive: false` everywhere
 * → still zero live claims. Times are relative so the fallback is never stale.
 */
const MINUTE = 60 * 1000;
const at = (m: number) => new Date(Date.now() + m * MINUTE).toISOString();

export function curatedFallback(now: number): Activity[] {
  const checked = new Date(now).toISOString();
  const base: Omit<Activity, 'lastCheckedAt'>[] = [
    {
      id: 'curated:jamboree-jam',
      title: 'Jamboree Jam Session',
      activityLabel: 'Live jazz',
      shortMapLabel: 'JAZZ',
      venueName: 'Jamboree',
      neighborhood: 'Plaça Reial · Gòtic',
      category: 'music',
      mood: 'late_night',
      coordinates: { lng: 2.1749, lat: 41.3795 },
      startsAt: at(-40),
      endsAt: at(110),
      sourceType: 'listings',
      sourceName: 'Jamboree',
      sourceUrl: 'https://www.jamboreejazz.com',
      verificationStatus: 'verified',
      verifiedLive: false,
      confidenceLevel: 0.8,
      importance: 0.7,
      priceLabel: 'From €12',
      description: 'Late-night jazz jam in a Plaça Reial cellar.',
      tags: ['jazz', 'live music'],
    },
    {
      id: 'curated:macba-night',
      title: 'MACBA: Night Galleries',
      activityLabel: 'Museum late',
      shortMapLabel: 'ART',
      venueName: 'MACBA',
      neighborhood: 'El Raval',
      category: 'exhibition',
      mood: 'cultural',
      coordinates: { lng: 2.1664, lat: 41.3831 },
      startsAt: at(-110),
      endsAt: at(35),
      sourceType: 'official',
      sourceName: 'MACBA',
      sourceUrl: 'https://www.macba.cat',
      verificationStatus: 'official_source',
      verifiedLive: false,
      confidenceLevel: 0.9,
      importance: 0.6,
      priceLabel: '€6',
      description: 'After-hours access to the contemporary collection.',
      tags: ['museum', 'art'],
    },
    {
      id: 'curated:apolo-club',
      title: 'Sala Apolo · Club Night',
      activityLabel: 'Indie club night',
      shortMapLabel: 'CLUB',
      venueName: 'Sala Apolo',
      neighborhood: 'Poble-sec',
      category: 'nightlife',
      mood: 'energetic',
      coordinates: { lng: 2.1686, lat: 41.3741 },
      startsAt: at(22),
      endsAt: at(320),
      sourceType: 'listings',
      sourceName: 'Sala Apolo',
      sourceUrl: 'https://www.sala-apolo.com',
      verificationStatus: 'verified',
      verifiedLive: false,
      confidenceLevel: 0.8,
      importance: 0.75,
      priceLabel: 'From €15',
      description: 'The legendary indie-rock club night on Paral·lel.',
      tags: ['indie', 'club'],
    },
    {
      id: 'curated:palau-quartet',
      title: 'Candlelight String Quartet',
      activityLabel: 'Classical concert',
      shortMapLabel: 'CLASSICAL',
      venueName: 'Palau de la Música Catalana',
      neighborhood: 'Sant Pere',
      category: 'music',
      mood: 'cultural',
      coordinates: { lng: 2.1753, lat: 41.3875 },
      startsAt: at(150),
      endsAt: at(240),
      sourceType: 'official',
      sourceName: 'Palau de la Música',
      sourceUrl: 'https://www.palaumusica.cat',
      verificationStatus: 'verified',
      verifiedLive: false,
      confidenceLevel: 0.82,
      importance: 0.8,
      priceLabel: 'From €25',
      description: 'Vivaldi by candlelight in a modernist jewel-box hall.',
      tags: ['classical', 'concert'],
    },
    {
      id: 'curated:santa-caterina-supper',
      title: 'Market Supper Club',
      activityLabel: 'Food pop-up',
      shortMapLabel: 'FOOD',
      venueName: 'Mercat de Santa Caterina',
      neighborhood: 'El Born',
      category: 'food',
      mood: 'social',
      coordinates: { lng: 2.1764, lat: 41.3866 },
      startsAt: at(95),
      endsAt: at(215),
      sourceType: 'curated',
      sourceName: 'NOW curation',
      verificationStatus: 'curated',
      verifiedLive: false,
      confidenceLevel: 0.5,
      importance: 0.55,
      priceLabel: '€€',
      description: 'A communal long-table dinner under the wave-tiled roof.',
      tags: ['food', 'supper club'],
    },
    {
      id: 'curated:sonar-by-day',
      title: 'Sónar by Day',
      activityLabel: 'Festival',
      shortMapLabel: 'FESTIVAL',
      venueName: 'Fira Barcelona Montjuïc',
      neighborhood: 'Montjuïc',
      category: 'music',
      mood: 'energetic',
      coordinates: { lng: 2.141, lat: 41.354 },
      startsAt: at(1200),
      endsAt: at(1650),
      sourceType: 'official',
      sourceName: 'Sónar',
      sourceUrl: 'https://sonar.es',
      verificationStatus: 'verified',
      verifiedLive: false,
      confidenceLevel: 0.85,
      importance: 0.9,
      priceLabel: 'From €65',
      description: 'Daytime stages of the electronic & advanced music festival.',
      tags: ['festival', 'electronic'],
    },
  ];

  return base.map((a) => ({ ...a, lastCheckedAt: checked }));
}
